version: "3.8"
services:
  besu:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: --miner-enabled --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73 --rpc-http-cors-origins="all" --host-allowlist="*" --rpc-ws-enabled --rpc-http-enabled --data-path=/opt/besu/datadir
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - type: volume
        source: besu_data
        target: /opt/besu/datadir

volumes:
  besu_data: